### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by Yang-505** [liub1934/uni-lb-tabbar#1]
大佬你好,请问怎么跳转到指定的tab 使用啥方法

**Comment by Yang-505** [comment]
项目是app 然后原生的tabBar可能效果不佳,所有用了自定义的, 问题刚刚我好像解决了, 通过 this.$emit（） 子传父 然后我没有通过onLoad 参数 进行更新, 而是直接 拿到子组件传过来的 name 直接赋值在 this.active上的 请问大概通过 onLoad（params）怎么传.....有点懵 谢谢大佬的插件,看到请回复一下下..

**Comment by liub1934** [comment]
可以参考下[Demo6](https://github.com/liub1934/uni-lb-tabbar/blob/master/pages/demos/demo6/demo6.vue#L95)
